In [7]:
import numpy as np
import matplotlib.pyplot as plt
from matplotlib import animation
import os
from IPython.display import HTML

In [2]:
# Load the image from the .npy file
image = np.load("data/processed/brain_extracted/IMG0001.npy")
print(f"Processing {image}: shape {image.shape}")


Processing [[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]: shape (243, 207)


In [8]:
import numpy as np
import matplotlib.pyplot as plt
from matplotlib import animation
import os

def load_npy_files(npy_dir):
    """Loads and sorts .npy files from a directory into a 3D numpy array."""
    files = [os.path.join(npy_dir, f) for f in sorted(os.listdir(npy_dir)) if f.endswith('.npy')]
    volumes = [np.load(f) for f in files]
    volume = np.stack(volumes)
    return volume

def create_animation(volume):
    """Creates an animation from a 3D numpy array."""
    ims = []
    fig, ax = plt.subplots()  # Create a figure and a set of subplots

    # Iterate through each slice of the volume
    for i in range(volume.shape[0]):  # Correctly iterate over the first dimension
        im = ax.imshow(volume[i], animated=True, cmap='gray')
        ims.append([im])

    ani = animation.ArtistAnimation(fig, ims, interval=50)  # Adjust interval as needed
    plt.close(fig)  # Close the figure to prevent it from displaying statically
    return ani

def main(npy_dir):
    volume = load_npy_files(npy_dir)
    ani = create_animation(volume)
    # Convert the animation to an HTML5 video and display it within the notebook
    return HTML(ani.to_html5_video())

if __name__ == "__main__":
    npy_dir = 'data/processed/resampled'  # Adjust as necessary
    display(main(npy_dir))
